const translations = {
  en: {
    // Shared Translations (from index.html)
    title: "Creative Rising Minds",
    brand_name: "Creative Rising Minds",
    nav_home: "Home",
    nav_indicators: "Indicators",
    nav_pricing: "Pricing",
    nav_contact: "Contact",
    footer_copyright: "© 2025 Creative Rising Minds. All rights reserved.",
    // indicator1.html Translations
    indicator_title: "CRM Trend Analyser",
    view_tradingview: "📈 View on TradingView",
    main_heading_trend: "💡 CRM Trend Analyser PRO– <span class='highlight'>Smart Entry Level Alert Tool</span> 💡",
    subheading: "Entry-Level | Multi-Timeframe | All Segment Support",
    feature_breakout_title: "✅ Breakout-Based Trading System",
    feature_breakout_1: "Detects breakout zones using <span class='highlight'>custom price structure</span> and <span class='highlight'>moving average logic</span>",
    feature_breakout_2: "Shows <span class='highlight'>early pre-entry cues</span> based on key highs/lows",
    feature_breakout_3: "Automatically calculates <span class='highlight'>Entry, Stop Loss, TP1, TP2, and TP3</span>",
    feature_trend_engine_title: "✅ Dynamic Trend Engine",
    feature_trend_engine_1: "Adaptive trend lines using momentum acceleration logic",
    feature_trend_engine_2: "Candle coloring based on trend speed for visual clarity",
    feature_trend_engine_3: "Gradient intensity reflects trend strength and stability",
    feature_timeframe_title: "✅ Multi-Timeframe Support",
    feature_timeframe_1: "Plots Daily/Weekly High, Low, and Close levels",
    feature_timeframe_2: "Make decisions using top-down market context",
    feature_timeframe_3: "Toggle historical levels + resize labels for visual comfort",
    feature_risk_management_title: "✅ Risk & Target Management",
    feature_risk_management_1: "Auto-calculated Entry, SL, TP1, TP2, TP3 based on multiple confluences",
    feature_risk_management_2: "Clearly plotted lines and levels for real-time decision-making",
    feature_risk_management_3: "Choose between <span class='highlight'>'Only Last Signal'</span> or <span class='highlight'>'All Signals'</span> mode:",
    feature_risk_management_4: "✅ Clean charts with most recent trade only",
    feature_risk_management_5: "✅ Back test easily with full signal history",
    feature_technical_tools_title: "✅ Built-in Technical Tools",
    feature_technical_tools_1: "Custom-styled <span class='highlight'>VWAP Overlay</span>",
    feature_technical_tools_2: "Demand & Supply zones for support/resistance",
    feature_technical_tools_3: "Multiple adaptive MAs with momentum tracking",
    feature_technical_tools_4: "MA gradient for strength confirmation",
    feature_signal_display_title: "✅ Smart Signal Display",
    feature_signal_display_1: "Dynamic Buy/Sell markers with entry labels",
    feature_signal_display_2: "Color-coded SL/TP lines for fast visual understanding",
    feature_signal_display_3: "Optional: Use standard candle colors",
    feature_signal_display_4: "Customize theme for your visual comfort",
    feature_timeframes_title: "🕒 Recommended Timeframes",
    feature_timeframes_1: "<span class='highlight'>3min / 5min → Intraday & Scalping</span>",
    feature_timeframes_2: "<span class='highlight'>Daily Chart → Swing / Positional setups</span>",
    feature_learning_note_title: "⚠️ Important Learning Note",
    feature_learning_note_intro: "This tool is meant to aid your learning and strategy development. Use it with:",
    feature_learning_note_1: "A clear trading plan",
    feature_learning_note_2: "Disciplined risk management",
    feature_learning_note_3: "Correct position sizing (start with single quantity)",
    feature_learning_note_4: "Strict Stop Loss rules",
    feature_learning_note_5: "Trade only when the risk-to-reward ratio is favorable",
    feature_learning_note_6: "In a sideways or opposing market, no trade can be the best trade",
    feature_learning_note_7: "True wealth creation happens only through long-term investing",
    feature_learning_note_8: "For disciplined risk management, limit intraday exposure to 10% of your capital",
    feature_beginner_path_title: "🔰 Beginner Path:",
    feature_beginner_path_1: "Start with paper trading for 2 months.",
    feature_beginner_path_2: "Then try equity trades with small capital (₹3,000 or less).",
    feature_beginner_path_3: "Limit loss to ₹50 – ₹100/day. Learn without pressure.",
    feature_beginner_path_4: "Avoid option/futures trading initially — options are high-risk instruments and require advanced understanding.",
    feature_beginner_path_quote: "<span class='highlight'>💡 “Learn first, earn later.” Your capital’s growth or loss is entirely in your control.</span>",
    feature_dark_mode_title: "🎨 Dark Mode Optimized → Now Fully Customizable",
    feature_dark_mode_desc: "Previously tailored for dark mode, now enhanced with user-selectable color options for a personalized and clear visual experience.",
    feature_trend_confluence_title: "📈 Dynamic Trend Confluence Visual",
    feature_trend_confluence_desc: "Introducing a trend-following visual layer to help you ride trends with confidence and clarity.",
    feature_alerts_title: "🔔 Real-Time Alerts Integrated",
    feature_alerts_desc: "Never miss a trade. Stay updated with built-in alerts for all key trade signals and conditions.",
    feature_disclaimer_title: "⚠️ Disclaimer",
    feature_disclaimer_1: "This indicator and content are intended purely for educational and informational purposes. They do not constitute financial, investment, or legal advice. All opinions are personal interpretations based on research and are not recommendations to buy, sell, or hold any security.",
    feature_disclaimer_2: "Always consult a SEBI-registered advisor or certified financial planner before making investment decisions. The creator is not responsible for any financial loss or decision taken by viewers.",
    feature_disclaimer_3: "Use this tool as support to your own strategy — not as a standalone trading system.",
    feature_disclaimer_4: "<strong>Happy Trading, CHEERS!</strong>",
    // Existing translations from index.html
    video_fallback: "Your browser does not support the video tag.",
    hero_title: "Built for Traders Who<br>Follow Logic,<br>Not Luck.",
    hero_subtitle: "Spot the Signal. Skip the Noise. Dominate the Trend.",
    hero_btn_explore: "Explore Plans",
    hero_btn_contact: "Contact Us",
    indicators_title: "Our Creative Indicators (Premium)",
    indicator_trend_title: 'CRM Trend Analyser PRO (Free Trial)',
    indicator_trend_desc: "<strong>CRM Trend Analyser PRO blends moving averages, trend oscillators, volatility targets, and supply-demand zones to help traders time entries and exits with precision.</strong>",
    indicator_learn_more: "Learn More",
    indicator_scalp_title: "CRM<br>Scalp / Swing",
    indicator_scalp_desc: "",
    indicator_demand_title: "CRM MTF/Demand Supply",
    indicator_demand_desc: "<strong>CRM MTF/Demand Supply is a smart trend-tracking tool that shows a multi-timeframe trend table and auto-plots demand/supply zones—so you can spot market direction and key levels without switching charts.</strong>",
    indicator_screener_title: "CRM Stock Screener",
    indicator_screener_desc: "CRM Stock Screener",
    indicator_option_title: "CRM Option Chain Decoder",
    indicator_option_desc: "CRM Option Chain Decoder",
    pricing_title: "Pricing Plans",
    pricing_table_indicator: "Indicator",
    pricing_table_monthly: "Monthly",
    pricing_table_quarterly: "Quarterly",
    pricing_table_half_yearly: "Half-Yearly",
    pricing_table_yearly: "Yearly",
    pricing_trend_status: "<strong><span style='color: #ff9800'>Free to use for a limited time – don’t miss out!</span></strong>",
    pricing_coming_soon: "Coming soon! Our team is crafting something powerful just for you.",
    feedback_text: "<span style='color: #ff9800'>We’d love to hear your valuable feedback on our indicators! Feel free to share your thoughts with us via WhatsApp, email, or Telegram.</span>",
    feedback_offer: "Share your feedback and stand a chance to win a free 1-month access to our premium indicator!",
    contact_title: "Contact & Payment",
    contact_subtitle: "Reach out for subscriptions, support, or payment queries.",
    telegram_handle: "@CREATIVE RISING MINDS",
    upi_title: "UPI Payment",
    upi_instruction: "Pay using UPI ID:<br><span>riazshaikh005@okicici</span>",
    upi_confirmation: "Share confirmation via WhatsApp or Telegram.",
    //footer
    footer_social_media: "Follow us on social media",
    footer_contact_us: "Contact Us",
    footer_email_label: "creativerisingminds@gmail.com",
    footer_phone_label: "+91 9930752555 (Enquiries)",
    footer_quick_links: "Quick Links",
    footer_policies: "Policies and Compliance",
    footer_home: "Home",
    footer_disclaimer: "Disclaimer",
    footer_privacy_policy: "Privacy Policy",
    footer_terms_conditions: "Terms and Conditions",
    // New Disclaimer Page Translations
    disclaimer_title: "Disclaimer | CRM",
    disclaimer_heading: "Disclaimer",
    risk_warning: "Investments in securities market are subject to market risks, read all the related documents carefully before investing.",
    section_intro: "Welcome to <strong>Creative Rising Minds (CRM)</strong>. All content and services provided through this website are for <strong>educational and informational purposes only</strong>.",
    section_not_financial_advice_title: "Not Financial Advice",
    section_not_financial_advice: "We are not SEBI registered advisors. Any information shared on this platform, including our tools, indicators, tutorials, or opinions, should not be considered as financial advice or recommendations to buy, sell, or hold any securities.",
    section_use_at_own_risk_title: "Use at Your Own Risk",
    section_use_at_own_risk: "Trading in the stock market involves risk. Past performance does not guarantee future returns. You are solely responsible for your investment decisions, and CRM or its team will not be liable for any losses incurred.",
    section_accuracy_content_title: "Accuracy & Content",
    section_accuracy_content: "We strive to provide accurate and updated information, but we do not make any warranties regarding the correctness, completeness, or reliability of any content. Always verify information independently before acting on it.",
    section_affiliate_content_title: "Affiliate & Promotional Content",
    section_affiliate_content: "Our website may contain affiliate links or promotional content. We may earn a small commission when you use these links, at no extra cost to you. However, we only promote tools or platforms we believe are valuable to users.",
    section_third_party_links_title: "Third-Party Links",
    section_third_party_links: "This site may contain links to third-party websites. We are not responsible for the content, policies, or practices of any external sites. Please review their respective terms and disclaimers.",
    section_consent_title: "Consent",
    section_consent: "By using this website, you hereby consent to this disclaimer and agree to its terms.",
    footer_note_contact: "If you have any questions about this disclaimer, feel free to contact us at <a href='mailto:creativerisingminds@gmail.com'>creativerisingminds@gmail.com</a>.",
    footer_note_updated: "Last updated: July 28, 2025",
    // New Privacy Policy Page Translations
    privacy_title: "Privacy Policy | CRM",
    privacy_policy_heading: "Privacy Policy",
    section_intro: "At <strong>Creative Rising Minds (CRM)</strong>, we value your privacy and are committed to protecting your personal information.",
    section_info_collect_title: "Information We Collect",
    section_info_collect: "We may collect personal identification information (such as your name, email address, and contact details) when you voluntarily submit it through forms, newsletter signups, or communication with us.",
    section_how_use_info_title: "How We Use Your Information",
    section_how_use_info: "The information we collect may be used to:",
    section_how_use_info_item1: "Respond to your queries and support requests",
    section_how_use_info_item2: "Send periodic emails about updates, tutorials, or tools",
    section_how_use_info_item3: "Improve our website’s performance and user experience",
    section_cookies_title: "Cookies",
    section_cookies: "We may use cookies to enhance your browsing experience. You can choose to disable cookies through your browser settings.",
    section_third_party_services_title: "Third-Party Services",
    section_third_party_services: "We may use third-party tools like analytics or affiliate platforms. These services may collect data as per their own privacy policies. We are not responsible for the data practices of these third-party sites.",
    section_data_security_title: "Data Security",
    section_data_security: "We take reasonable measures to protect your data, but no transmission over the internet is 100% secure. We cannot guarantee absolute security.",
    section_external_links_title: "External Links",
    section_external_links: "Our website may contain links to other websites. We are not responsible for the privacy practices of those sites and encourage you to read their privacy policies.",
    section_your_consent_title: "Your Consent",
    section_your_consent: "By using our website, you consent to this Privacy Policy and agree to its terms.",
    section_changes_policy_title: "Changes to This Policy",
    section_changes_policy: "We may update this policy from time to time. Changes will be posted on this page with an updated revision date.",
    footer_note_contact: "If you have any questions regarding this Privacy Policy, contact us at <a href='mailto:creativerisingminds@gmail.com'>creativerisingminds@gmail.com</a>.",
    footer_note_updated: "Last updated: July 28, 2025",
    // New Terms and Conditions Page Translations
    tnc_title: "Terms and Conditions | CRM",
    terms_conditions_heading: "Terms and Conditions",
    section_intro: "Welcome to <strong>Creative Rising Minds (CRM)</strong>. By accessing this website, you agree to comply with and be bound by the following terms and conditions. If you disagree with any part of these terms, please do not use our website.",
    section_use_content_title: "Use of Content",
    section_use_content: "All content on this website, including trading indicators, tutorials, and branding, is the property of CRM and is protected by copyright laws. You may not reproduce, distribute, or exploit any content without prior written consent.",
    section_disclaimer_title: "Disclaimer",
    section_disclaimer: "All trading indicators, signals, or tools provided on this website are for educational and informational purposes only. We are not registered financial advisors and do not offer any investment advice. You are solely responsible for your trading decisions.",
    section_payments_subscriptions_title: "Payments and Subscriptions",
    section_payments_subscriptions: "All payments made for our products or services are final and non-refundable unless otherwise stated. You agree to provide accurate and complete payment details when making purchases on our platform.",
    section_limitation_liability_title: "Limitation of Liability",
    section_limitation_liability: "CRM shall not be liable for any direct, indirect, or consequential losses or damages arising from the use of our website or products. You agree to use our services at your own risk.",
    section_user_conduct_title: "User Conduct",
    section_user_conduct: "You agree not to use this site for any unlawful purpose or in any way that may harm CRM or other users. Misuse of this site may result in termination of your access.",
    section_external_links_title: "External Links",
    section_external_links: "We may include links to third-party websites. These links are provided for your convenience and do not signify our endorsement. We are not responsible for the content or practices of these external sites.",
    section_modifications_title: "Modifications",
    section_modifications: "We may revise these Terms and Conditions from time to time. The latest version will always be posted on this page. Continued use of our site implies your acceptance of these changes.",
    section_governing_law_title: "Governing Law",
    section_governing_law: "These terms are governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in Mumbai.",
    footer_note_contact: "If you have any questions about these Terms and Conditions, feel free to contact us at <a href='mailto:creativerisingminds@gmail.com'>creativerisingminds@gmail.com</a>.",
    footer_note_updated: "Last updated: July 28, 2025",
    free_indicators_title: "Our Free Indicators",
    indicator_momentum_title: "CRM Momentum Finder",
    indicator_volatility_title : "CRM Volatility Tracker",
    indicator_scalp_desc : "<strong>CRM Scalp/Swing is a versatile indicator designed for both scalping and swing trading, offering precise signals for quick trades and longer-term strategies.</strong>",
    indicator_scalp_price_title : "CRM Scalp / Swing Indicator",
    //demand supply translations
    main_heading_demand : "💡 CRM MTF / Demand Supply– <span class='highlight'>Seamless Scalps. Strategic Swings</span> 💡",
    //scalp swing translations
    main_heading_scalp : "💡 CRM Scalp/ Swing– <span class=highlight'>Seamless Scalps. Strategic Swings</span> 💡"
  },
  gu: {
    // Shared Translations
    title: "ક્રિએટિવ રાઇઝિંગ માઇન્ડ્સ",
    brand_name: "ક્રિએટિવ રાઇઝિંગ માઇન્ડ્સ",
    nav_home: "હોમ",
    nav_indicators: "સૂચકો",
    nav_pricing: "કિંમત",
    nav_contact: "સંપર્ક",
    footer_copyright: "© 2025 ક્રિએટિવ રાઇઝિંગ માઇન્ડ્સ. સર્વાધિકાર સુરક્ષિત.",
    // indicator1.html Translations
    indicator_title: "CRM ટ્રેન્ડ એનાલાઇઝર",
    view_tradingview: "📈 ટ્રેડિંગવ્યૂ પર જુઓ",
    main_heading_trend: "💡 CRM ટ્રેન્ડ એનાલાઇઝર પ્રો– <span class='highlight'>સ્માર્ટ એન્ટ્રી લેવલ એલર્ટ ટૂલ</span> 💡",
    subheading: "એન્ટ્રી-લેવલ | મલ્ટી-ટાઇમફ્રેમ | બધા સેગમેન્ટ સપોર્ટ",
    feature_breakout_title: "✅ બ્રેકઆઉટ-આધારિત ટ્રેડિંગ સિસ્ટમ",
    feature_breakout_1: "<span class='highlight'>કસ્ટમ પ્રાઇસ સ્ટ્રક્ચર</span> અને <span class='highlight'>મૂવિંગ એવરેજ લોજિક</span> નો ઉપયોગ કરીને બ્રેકઆઉટ ઝોન શોધે છે",
    feature_breakout_2: "મુખ્ય ઉચ્ચ/નીચા આધારે <span class='highlight'>વહેલા પ્રી-એન્ટ્રી સંકેતો</span> બતાવે છે",
    feature_breakout_3: "<span class='highlight'>એન્ટ્રી, સ્ટોપ લોસ, TP1, TP2, અને TP3</span> આપોઆપ ગણે છે",
    feature_trend_engine_title: "✅ ડાયનામિક ટ્રેન્ડ એન્જિન",
    feature_trend_engine_1: "મોમેન્ટમ એક્સેલરેશન લોજિકનો ઉપયોગ કરીને એડેપ્ટિવ ટ્રેન્ડ લાઇન્સ",
    feature_trend_engine_2: "ટ્રેન્ડની ઝડપના આધારે મીણબત્તીનો રંગ દર્શાવવો",
    feature_trend_engine_3: "ગ્રેડિયન્ટની તીવ્રતા ટ્રેન્ડની શક્તિ અને સ્થિરતા દર્શાવે છે",
    feature_timeframe_title: "✅ મલ્ટી-ટાઇમફ્રેમ સપોર્ટ",
    feature_timeframe_1: "દૈનિક/સાપ્તાહિક ઉચ્ચ, નીચું અને બંધ સ્તરો દર્શાવે છે",
    feature_timeframe_2: "ટોપ-ડાઉન માર્કેટ સંદર્ભનો ઉપયોગ કરીને નિર્ણયો લો",
    feature_timeframe_3: "ઐતિહાસિક સ્તરો ટૉગલ કરો + લેબલ્સનું કદ બદલો",
    feature_risk_management_title: "✅ જોખમ અને લક્ષ્ય વ્યવસ્થાપન",
    feature_risk_management_1: "બહુવિધ સંગમના આધારે આપોઆપ ગણેલ એન્ટ્રી, SL, TP1, TP2, TP3",
    feature_risk_management_2: "રીઅલ-ટાઇમ નિર્ણય લેવા માટે સ્પષ્ટ રેખાઓ અને સ્તરો",
    feature_risk_management_3: "<span class='highlight'>'ફક્ત છેલ્લું સિગ્નલ'</span> અથવા <span class='highlight'>'બધા સિગ્નલ'</span> મોડ વચ્ચે પસંદગી કરો:",
    feature_risk_management_4: "✅ ફક્ત તાજેતરના વેપાર સાથે સ્વચ્છ ચાર્ટ",
    feature_risk_management_5: "✅ સંપૂર્ણ સિગ્નલ ઇતિહાસ સાથે સરળતાથી બેક ટેસ્ટ",
    feature_technical_tools_title: "✅ બિલ્ટ-ઇન ટેકનિકલ ટૂલ્સ",
    feature_technical_tools_1: "કસ્ટમ-styled <span class='highlight'>VWAP ઓવરલે</span>",
    feature_technical_tools_2: "સપોર્ટ/પ્રતિકાર માટે માંગ અને પૂરવઠા ઝોન",
    feature_technical_tools_3: "મોમેન્ટમ ટ્ર tracking સાથે બહુવિધ એડેપ્ટિવ MA",
    feature_technical_tools_4: "શક્તિ પુષ્ટિકરણ માટે MA ગ્રેડિયન્ટ",
    feature_signal_display_title: "✅ Smart Signal Display",
    feature_signal_display_1: "એન્ટ્રી લેબલ્સ સાથે ડાયનામિક ખરીદો/વેચો માર્કર્સ",
    feature_signal_display_2: "ઝડપી દ્રશ્ય સમજણ માટે રંગ-કોડેડ SL/TP રેખાઓ",
    feature_signal_display_3: "વૈકલ્પિક: પ્રમાણભૂત મીણબત્તી રંગોનો ઉપયોગ કરો",
    feature_signal_display_4: "દ્રશ્ય આરામ માટે થીમ કસ્ટમાઇઝ કરો",
    feature_timeframes_title: "🕒 ભલામણ કરેલ ટાઇમફ્રેમ",
    feature_timeframes_1: "<span class='highlight'>3 મિનિટ / 5 મિનિટ → ઇન્ટ્રાડે અને સ્કેલ્પિંગ</span>",
    feature_timeframes_2: "<span class='highlight'>દૈનિક ચાર્ટ → સ્વિંગ / પોઝિશનલ સેટઅપ્સ</span>",
    feature_learning_note_title: "⚠️ મહત્વની શીખવાની નોંધ",
    feature_learning_note_intro: "આ ટૂલ તમારા શિક્ષણ અને વ્યૂહરચના વિકાસ માટે મદદ કરવા માટે બનાવેલ છે. તેનો ઉપયોગ આની સાથે કરો:",
    feature_learning_note_1: "સ્પષ્ટ ટ્રેડિંગ યોજના",
    feature_learning_note_2: "શિસ્તબદ્ધ જોખમ વ્યવસ્થાપન",
    feature_learning_note_3: "યોગ્ય સ્થિતિનું કદ (એક જ માત્રાથી શરૂ)",
    feature_learning_note_4: "કડક સ્ટોપ લોસ નિયમો",
    feature_learning_note_5: "જ્યારે જોખમ-થી-પુરસ્કાર ગુણોત્તર અનુકૂળ હોય ત્યારે જ ટ્રેડ",
    feature_learning_note_6: "બાજુના અથવા વિરોધી બજારમાં, કોઈ ટ્રેડ ન કરવું શ્રેષ્ઠ ટ્રેડ હોઈ શકે",
    feature_learning_note_7: "સાચું ધન નિર્માણ ફક્ત લાંબા-ગાળાના રોકાણ દ્વારા થાય છે",
    feature_learning_note_8: "શિસ્તબદ્ધ જોખમ વ્યવસ્થાપન માટે, ઇન્ટ્રાડે એક્સપોઝરને તમારી મૂડીના 10% સુધી મર્યાદિત કરો",
    feature_beginner_path_title: "🔰 શિખાઉ માર્ગ:",
    feature_beginner_path_1: "2 મહિના માટે પેપર ટ્રેડિંગથી શરૂઆત કરો.",
    feature_beginner_path_2: "પછી નાની મૂડી (₹3,000 કે ઓછી) સાથે ઇક્વિટી ટ્રેડ અજમાવો.",
    feature_beginner_path_3: "નુકસાન ₹50 – ₹100/દિવસ સુધી મર્યાદિત કરો. દબાણ વિના શીખો.",
    feature_beginner_path_4: "શરૂઆતમાં ઓપ્શન/ફ્યુચર્સ ટ્રેડિંગ ટાળો — ઓપ્શન્સ ઉચ્ચ-જોખમી સાધનો છે અને તેના માટે અદ્યતન સમજની જરૂર છે.",
    feature_beginner_path_quote: "<span class='highlight'>💡 “પહેલા શીખો, પછી કમાઓ.” તમારી મૂડીનો વિકાસ કે નુકસાન સંપૂર્ણપણે તમારા નિયંત્રણમાં છે.</span>",
    feature_dark_mode_title: "🎨 ડાર્ક મોડ માટે ઑપ્ટિમાઇઝ → હવે સંપૂર્ણ કસ્ટમાઇઝેબલ",
    feature_dark_mode_desc: "પહેલા ડાર્ક મોડ માટે રચાયેલ, હવે વપરાશકર્તા-પસંદગીના રંગ વિકલ્પો સાથે વધારેલ, વ્યક્તિગત અને સ્પષ્ટ દ્રશ્ય અનુભવ માટે.",
    feature_trend_confluence_title: "📈 ડાયનામિક ટ્રેન્ડ કોન્ફલ્યુએન્સ વિઝ્યુઅલ",
    feature_trend_confluence_desc: "ટ્રેન્ડ-અનુસરણ વિઝ્યુઅલ લેયર રજૂ કરીએ છીએ જે તમને આત્મવિશ્વાસ અને સ્પષ્ટતા સાથે ટ્રેન્ડને ફોલો કરવામાં મદદ કરે.",
    feature_alerts_title: "🖥️ રિયલ-ટાઇમ એલર્ટ્સ ઇન્ટિગ્રેટેડ",
    feature_alerts_desc: "ક્યારેય ટ્રેડ ચૂકશો નહીં. તમામ મુખ્ય ટ્રેડ સિગ્નલો અને શરતો માટે બિલ્ટ-ઇન એલર્ટ્સ સાથે અદ્યતન રહો.",
    feature_disclaimer_title: "⚠️ ડિસ્ક્લેમર",
    feature_disclaimer_1: "આ સૂચક અને સામગ્રી ફક્ત શૈક્ષણિક અને માહિતીના હેતુઓ માટે છે. તે નાણાકીય, રોકાણ, કે કાનૂની સલાહ નથી. બધા મંતવ્યો સંશોધન આધારિત વ્યક્તિગત અર્થઘટન છે અને કોઈ સિક્યોરિટી ખરીદવા, વેચવા, કે હોલ્ડ કરવાની ભલામણ નથી.",
    feature_disclaimer_2: "રોકાણના નિર્ણયો લેતા પહેલા હંમેશા SEBI-નોંધાયેલ સલાહકાર અથવા પ્રમાણિત નાણીય આયોજકની સલાહ લો. સર્જક દર્શકો દ્વારા લેવાયેલ કોઈ નાણીય નુકસાન કે નિર્ણય માટે જવાબદાર નથી.",
    feature_disclaimer_3: "આ ટૂલ તમારી પોતાની વ્યૂહરચનાના સમર્થન માટે વાપરો — એકલા ટ્રેડિંગ સિસ્ટમ તરીકે નહી.",
    feature_disclaimer_4: "<strong>આનંદી ટ્રેડિંગ, ચીય! </strong>",
    // Existing translations...
    video_fallback: "તમારું બ્રાઉઝર વિડિઓ ટેગને સપોર્ટ કરતું નથી.",
    hero_title: "ટ્રેડર્સ માટે બનાવેલ જેઓ<br>તર્કને અનુસરે છે,<br>નસીબને નહીં.",
    hero_subtitle: "સિગ્નલ શોધો. અવાજને ટાળો. ટ્રેન્ડ પર પ્રભુત્વ મેળવો.",
    hero_btn_explore: "યોજનાઓ શોધો",
    hero_btn_contact: "અમારો સંપર્ક કરો",
    indicators_title: "અમારા ક્રિએટિવ સૂચકો (પ્રીમિયમ)",
    indicator_trend_title: 'CRM ટ્રેન્ડ એનાલાઇઝર પ્રો (મફત ટ્રાયલ)',
    indicator_trend_desc: "<strong>CRM ટ્રેન્ડ એનાલાઇઝર પ્રો એ મૂવિંગ એવરેજ, ટ્રેન્ડ ઓસિલેટર્સ, વોલેટિલિટી લક્ષ્યો અને સપ્લાઇ-ડિમાન્ડ ઝોન્સને મિલાવીને ટ્રેડરોને એન્ટ્રીઝ અને એક્ઝિટ્સનો સમય ચોકસાઈથી નક્કી કરવામાં મદદ કરે છે.</strong>",
    indicator_learn_more: "વધુ જાણો",
    indicator_scalp_title: "CRM<br>સ્કેલ્પ / સ્વિંગ",
    indicator_scalp_desc: "",
    indicator_demand_title: "CRM MTF/ડિમાન્ડ સપ્લાય",
    indicator_demand_desc: "<strong>CRM MTF/ડિમાન્ડ સપ્લાઇ એ એક સ્માર્ટ ટ્રેન્ડ-ટ્રેકિંગ ટૂલ છે જે મલ્ટી-ટાઇમફ્રેમ ટ્રેન્ડ ટેબલ દર્શાવે છે અને ડિમાન્ડ/સપ્લાઇ ઝોન્સને આપોઆપ દર્શાવે છે—જેથી તમે ચાર્ટ બદલ્યા વિના બજારની દિશા અને મુખ્ય સ્તરો શોધી શકો.</strong>",
    indicator_screener_title: "CRM સ્ટોક સ્ક્રીનર",
    indicator_screener_desc: "",
    indicator_option_title: "CRM ઓપ્શન ચેઇન ડીકોડર",
    indicator_option_desc: "",
    pricing_title: "કિંમત યોજનાઓ",
    pricing_table_indicator: "સૂચક",
    pricing_table_monthly: "માસિક",
    pricing_table_quarterly: "ત્રિમાસિક",
    pricing_table_half_yearly: "અર્ધ-વાર્ષિક",
    pricing_table_yearly: "વાર્ષિક",
    pricing_trend_status: "<strong><span style='color: #ff9800'>મર્યાદિત સમય માટે મફત વાપરો – ચૂકશો નહીં!</span></strong>",
    pricing_coming_soon: "ટૂંક સમયમાં આવી રહ્યું છે! અમારી ટીમ તમારા માટે કંઈક શક્તિશાળી બનાવી રહી છે.",
    feedback_text: "<span style='color: #ff9800'>અમે અમારા સૂચકો પર તમારા મૂલ્યવાન પ્રતિસાદ સાંભળવા માટે ઉત્સુક છીએ! WhatsApp, ઈમેલ અથવા ટેલિગ્રામ દ્વારા તમારા વિચારો અમારી સાથે શેર કરો.</span>",
    feedback_offer: "તમારો પ્રતિસાદ શેર કરો અને અમારા પ્રીમિયમ સૂચકની એક મહિનાની મફત ઍક્સેસ જીતવાની તક મેળવો!",
    contact_title: "સંપર્ક અને ચુકવણી",
    contact_subtitle: "સબ્સ્ક્રિપ્શન, સપોર્ટ અથવા ચુકવણી સંબંધિત પ્રશ્નો માટે સંપર્ક કરો.",
    telegram_handle: "@CREATIVE RISING MINDS",
    upi_title: "UPI ચુકવણી",
    upi_instruction: "UPI ID નો ઉપયોગ કરીને ચુકવણી કરો:<br><span>riazshaikh005@okicici</span>",
    upi_confirmation: "WhatsApp અથવા ટેલિગ્રામ દ્વારા પુષ્ટિ શેર કરો.",
    footer_social_media: "અમને સોશિયલ મીડિયા પર ફોલો કરો",
    footer_contact_us: "અમારો સંપર્ક કરો",
    footer_email_label: "creativerisingminds@gmail.com",
    footer_phone_label: "+91 9930752555 (પૂછપરછ)",
    footer_quick_links: "ઝડપી લિંક્સ",
    footer_policies: "નીતિઓ અને પાલન",
    footer_home: "હોમ",
    footer_disclaimer: "ડિસ્ક્લેમર",
    footer_privacy_policy: "ગોપનીયતા નીતિ",
    footer_terms_conditions: "નિયમો અને શરતો",
    // New Disclaimer Page Translations
    disclaimer_title: "ડિસ્ક્લેમર | CRM",
    disclaimer_heading: "ડિસ્ક્લેમર",
    risk_warning: "સિક્યોરિટીઝ બજારમાં રોકાણો બજારના જોખમોને આધીન છે, રોકાણ કરતા પહેલા બધા સંબંધિત દસ્તાવેજો ધ્યાનથી વાંચો.",
    section_intro: "<strong>ક્રિએટિવ રાઇઝિંગ માઇન્ડ્સ (CRM)</strong> માં આપનું સ્વાગત છે. આ વેબસાઇટ દ્વારા પૂરી પાડવામાં આવેલ તમામ સામગ્રી અને સેવાઓ માત્ર <strong>શૈક્ષણિક અને માહિતીના હેતુઓ માટે</strong> છે.",
    section_not_financial_advice_title: "નાણાકીય સલાહ નથી",
    section_not_financial_advice: "અમે SEBI નોંધાયેલ સલાહકારો નથી. આ પ્લેટફોર્મ પર શેર કરેલી કોઈપણ માહિતી, જેમાં અમારા સાધનો, સૂચકો, ટ્યુટોરિયલ્સ, અથવા મંતવ્યોનો સમાવેશ થાય છે, તે નાણાકીય સલાહ અથવા કોઈ સિક્યોરિટી ખરીદવા, વેચવા, અથવા હોલ્ડ કરવાની ભલામણ તરીકે ગણવી જોઈએ નહીં.",
    section_use_at_own_risk_title: "તમારા પોતાના જોખમે વાપરો",
    section_use_at_own_risk: "શેરબજારમાં ટ્રેડિંગમાં જોખમ સામેલ છે. ભૂતકાળનું પ્રદર્શન ભવિષ્યના વળતરની બાંયધરી આપતું નથી. તમે તમારા રોકાણના નિર્ણયો માટે સંપૂર્ણપણે જવાબદાર છો, અને CRM અથવા તેની ટીમ કોઈપણ નુકસાન માટે જવાબદાર રહેશે નહીં.",
    section_accuracy_content_title: "ચોકસાઈ અને સામગ્રી",
    section_accuracy_content: "અમે સચોટ અને અદ્યતન માહિતી પૂરી પાડવાનો પ્રયાસ કરીએ છીએ, પરંતુ અમે કોઈપણ સામગ્રીની ચોકસાઈ, સંપૂર્ણતા, અથવા વિશ્વસનીયતા અંગે કોઈ વોરંટી આપતા નથી. તેના પર કાર્ય કરતા પહેલા હંમેશા માહિતીની સ્વતંત્ર રીતે ચકાસણી કરો.",
    section_affiliate_content_title: "એફિલિએટ અને પ્રમોશનલ સામગ્રી",
    section_affiliate_content: "અમારી વેબસાઇટમાં એફિલિએટ લિંક્સ અથવા પ્રમોશનલ સામગ્રી હોઈ શકે છે. જ્યારે તમે આ લિંક્સનો ઉપયોગ કરો ત્યારે અમે નાનું કમિશન મેળવી શકીએ છીએ, તમને કોઈ વધારાનો ખર્ચ થયા વિના. જોકે, અમે ફક્ત તે સાધનો અથવા પ્લેટફોર્મ્સનું પ્રમોશન કરીએ છીએ જે અમને વપરાશકર્તાઓ માટે મૂલ્યવાન લાગે છે.",
    section_third_party_links_title: "તૃતીય-પક્ષ લિંક્સ",
    section_third_party_links: "આ સાઇટમાં તૃતીય-પક્ષ વેબસાઇટ્સની લિંક્સ હોઈ શકે છે. અમે બાહ્ય સાઇટ્સની સામગ્રી, નીતિઓ, અથવા પ્રથાઓ માટે જવાબદાર નથી. કૃપા કરીને તેમના સંબંધિત નિયમો અને ડિસ્ક્લેમર્સની સમીક્ષા કરો.",
    section_consent_title: "સંમતિ",
    section_consent: "આ વેબસાઇટનો ઉપયોગ કરીને, તમે આ ડિસ્ક્લેમરને સંમતિ આપો છો અને તેની શરતોનું પાલન કરવા સંમત થાઓ છો.",
    footer_note_contact: "જો તમને આ ડિસ્ક્લેમર વિશે કોઈ પ્રશ્નો હોય, તો કૃપા કરીને અમારો સંપર્ક કરો <a href='mailto:creativerisingminds@gmail.com'>creativerisingminds@gmail.com</a> પર.",
    footer_note_updated: "છેલ્લું અદ્યતન: જુલાઈ 28, 2025",
    // New Privacy Policy Page Translations
    privacy_title: "ગોપનીયતા નીતિ | CRM",
    privacy_policy_heading: "ગોપનીયતા નીતિ",
    section_intro: "<strong>ક્રિએટિવ રાઇઝિંગ માઇન્ડ્સ (CRM)</strong> ખાતે, અમે તમારી ગોપનીયતાને મૂલ્ય આપીએ છીએ અને તમારી વ્યક્તિગત માહિતીનું રક્ષણ કરવા માટે પ્રતિબદ્ધ છીએ.",
    section_info_collect_title: "અમે એકત્રિત કરીએ છીએ તે માહિતી",
    section_info_collect: "જ્યારે તમે ફોર્મ્સ, ન્યૂઝલેટર સાઇનઅપ્સ, અથવા અમારી સાથે સંચાર દ્વારા સ્વેચ્છાએ સબમિટ કરો ત્યારે અમે વ્યક્તિગત ઓળખ માહિતી (જેમ કે તમારું નામ, ઇમેઇલ સરનામું, અને સંપર્ક વિગતો) એકત્રિત કરી શકીએ છીએ.",
    section_how_use_info_title: "અમે તમારી માહિતીનો ઉપયોગ કેવી રીતે કરીએ છીએ",
    section_how_use_info: "અમે એકત્રિત કરેલી માહિતીનો ઉપયોગ આ માટે થઈ શકે છે:",
    section_how_use_info_item1: "તમારી પૂછપરછ અને સમર્થન વિનંતીઓનો જવાબ આપવા",
    section_how_use_info_item2: "અપડેટ્સ, ટ્યુટોરિયલ્સ, અથવા સાધનો વિશે સમયાંતરે ઇમેઇલ્સ મોકલવા",
    section_how_use_info_item3: "અમારી વેબસાઇટની કામગીરી અને વપરાશકર્તા અનુભવને સુધારવા",
    section_cookies_title: "કૂકીઝ",
    section_cookies: "અમે તમારા બ્રાઉઝિંગ અનુભવને વધારવા માટે કૂકીઝનો ઉપયોગ કરી શકીએ છીએ. તમે તમારા બ્રાઉઝર સેટિંગ્સ દ્વારા કૂકીઝને અક્ષમ કરવાનું પસંદ કરી શકો છો.",
    section_third_party_services_title: "તૃતીય-પક્ષ સેવાઓ",
    section_third_party_services: "અમે એનાલિટિક્સ અથવા એફિલિએટ પ્લેટફોર્મ્સ જેવા તૃતીય-પક્ષ સાધનોનો ઉપયોગ કરી શકીએ છીએ. આ સેવાઓ તેમની પોતાની ગોપનીયતા નીતિઓ અનુસાર ડેટા એકત્રિત કરી શકે છે. અમે આ તૃતીય-પક્ષ સાઇટ્સની ડેટા પ્રથાઓ માટે જવાબદાર નથી.",
    section_data_security_title: "ડેટા સુરક્ષા",
    section_data_security: "અમે તમારા ડેટાને સુરક્ષિત રાખવા માટે વાજબી પગલાં લઈએ છીએ, પરંતુ ઇન્ટરનેટ પર કોઈ ટ્રાન્સમિશન 100% સુરક્ષિત નથી. અમે સંપૂર્ણ સુરક્ષાની બાંયધરી આપી શકતા નથી.",
    section_external_links_title: "બાહ્ય લિંક્સ",
    section_external_links: "અમારી વેબસાઇટમાં અન્ય વેબસાઇટ્સની લિંક્સ હોઈ શકે છે. અમે તે સાઇટ્સની ગોપનીયતા પ્રથાઓ માટે જવાબદાર નથી અને તમને તેમની ગોપનીયતા નીતિઓ વાંચવા પ્રોત્સાહિત કરીએ છીએ.",
    section_your_consent_title: "તમારી સંમતિ",
    section_your_consent: "અમારી વેબસાઇટનો ઉપયોગ કરીને, તમે આ ગોપનીયતા નીતિને સંમતિ આપો છો અને તેની શરતોનું પાલન કરવા સંમત થાઓ છો.",
    section_changes_policy_title: "આ નીતિમાં ફેરફારો",
    section_changes_policy: "અમે આ નીતિમાં સમયાંતરે અપડેટ કરી શકીએ છીએ. ફેરફારો આ પૃષ્ઠ પર અપડેટેડ રિવિઝન તારીખ સાથે પોસ્ટ કરવામાં આવશે.",
    footer_note_contact: "જો તમને આ ગોપનીયતા નીતિ વિશે કોઈ પ્રશ્નો હોય, તો અમારો સંપર્ક કરો <a href='mailto:creativerisingminds@gmail.com'>creativerisingminds@gmail.com</a> પર.",
    footer_note_updated: "છેલ્લું અદ્યતન: જુલાઈ 28, 2025",
    // New Terms and Conditions Page Translations
    tnc_title: "નિયમો અને શરતો | CRM",
    terms_conditions_heading: "નિયમો અને શરતો",
    section_intro: "<strong>ક્રિએટિવ રાઇઝિંગ માઇન્ડ્સ (CRM)</strong> માં આપનું સ્વાગત છે. આ વેબસાઇટનો ઉપયોગ કરીને, તમે નીચેના નિયમો અને શરતોનું પાલન કરવા અને તેના દ્વારા બંધાયેલા રહેવા સંમત થાઓ છો. જો તમે આ શરતોના કોઈપણ ભાગ સાથે અસંમત હો, તો કૃપા કરીને અમારી વેબસાઇટનો ઉપયોગ કરશો નહીં.",
    section_use_content_title: "સામગ્રીનો ઉપયોગ",
    section_use_content: "આ વેબસાઇટ પરની તમામ સામગ્રી, જેમાં ટ્રેડિંગ સૂચકો, ટ્યુટોરિયલ્સ, અને બ્રાન્ડિંગનો સમાવેશ થાય છે, તે CRMની માલિકી છે અને કૉપિરાઇટ કાયદાઓ દ્વારા સુરક્ષિત છે. તમે પૂર્વ લેખિત સંમતિ વિના કોઈપણ સામગ્રીનું પુનઃઉત્પાદન, વિતરણ, અથવા શોષણ કરી શકતા નથી.",
    section_disclaimer_title: "ડિસ્ક્લેમર",
    section_disclaimer: "આ વેબસાઇટ પર પૂરી પાડવામાં આવેલ તમામ ટ્રેડિંગ સૂચકો, સિગ્નલ્સ, અથવા સાધનો માત્ર શૈક્ષણિક અને માહિતીના હેતુઓ માટે છે. અમે નોંધાયેલ નાણાકીય સલાહકારો નથી અને કોઈ રોકાણ સલાહ આપતા નથી. તમે તમારા ટ્રેડિંગ નિર્ણયો માટે સંપૂર્ણપણે જવાબદાર છો.",
    section_payments_subscriptions_title: "ચુકવણી અને સબસ્ક્રિપ્શન્સ",
    section_payments_subscriptions: "અમારા ઉત્પાદનો અથવા સેવાઓ માટે કરવામાં આવેલ તમામ ચુકવણીઓ અંતિમ અને નોન-રિફંડેબલ છે, સિવાય કે અન્યથા જણાવેલ હોય. તમે અમારા પ્લેટફોર્મ પર ખરીદી કરતી વખતે સચોટ અને સંપૂર્ણ ચુકવણી વિગતો પૂરી પાડવા સંમત થાઓ છો.",
    section_limitation_liability_title: "જવાબદારીની મર્યાદા",
    section_limitation_liability: "CRM અમારી વેબસાઇટ અથવા ઉત્પાદનોના ઉપયોગથી ઉદ્ભવતા કોઈપણ સીધા, પરોક્ષ, અથવા પરિણામલક્ષી નુકસાન અથવા હાનિ માટે જવાબદાર રહેશે નહીં. તમે અમારી સેવાઓનો ઉપયોગ તમારા પોતાના જોખમે કરવા સંમત થાઓ છો.",
    section_user_conduct_title: "વપરાશકર્તા આચરણ",
    section_user_conduct: "તમે આ સાઇટનો ઉપયોગ કોઈપણ ગેરકાયદેસર હેતુ માટે અથવા CRM અથવા અન્ય વપરાશકર્તાઓને નુકસાન પહોંચાડે તે રીતે નહીં કરવા સંમત થાઓ છો. આ સાઇટનો દુરુપયોગ તમારા ઍક્સેસની સમાપ્તિમાં પરિણમી શકે છે.",
    section_external_links_title: "બાહ્ય લિંક્સ",
    section_external_links: "અમે તૃતીય-પક્ષ વેબસાઇટ્સની લિંક્સ શામેલ કરી શકીએ છીએ. આ લિંક્સ તમારી સુવિધા માટે પૂરી પાડવામાં આવે છે અને અમારા સમર્થનને સૂચવતા નથી. અમે આ બાહ્ય સાઇટ્સની સામગ્રી અથવા પ્રથાઓ માટે જવાબદાર નથી.",
    section_modifications_title: "સુધારાઓ",
    section_modifications: "અમે આ નિયમો અને શરતોમાં સમયાંતરે સુધારો કરી શકીએ છીએ. નવીનતમ સંસ્કરણ હંમેશા આ પૃષ્ઠ પર પોસ્ટ કરવામાં આવશે. અમારી સાઇટનો સતત ઉપયોગ આ ફેરફારોની સ્વીકૃતિ દર્શાવે છે.",
    section_governing_law_title: "શાસન કાયદો",
    section_governing_law: "આ શરતો ભારતના કાયદાઓ અનુસાર શાસિત અને અર્થઘટન કરવામાં આવે છે. કોઈપણ વિવાદ મુંબઈની અદાલતોના વિશિષ્ટ અધિકારક્ષેત્રને આધીન રહેશે.",
    footer_note_contact: "જો તમને આ નિયમો અને શરતો વિશે કોઈ પ્રશ્નો હોય, તો કૃપા કરીને અમારો સંપર્ક કરો <a href='mailto:creativerisingminds@gmail.com'>creativerisingminds@gmail.com</a> પર.",
    footer_note_updated: "છેલ્લું અદ્યતન: જુલાઈ 28, 2025",
    free_indicators_title: "અમારા મફત સૂચકો",
    indicator_momentum_title: "CRM મોમેન્ટમ ફાઇન્ડર",
    indicator_volatility_title: "CRM વોલેટિલિટી ટ્રેકર",
    indicator_scalp_desc: "<strong>CRM સ્કેલ્પ/સ્વિંગ એ એક વર્સેટાઇલ સૂચક છે જે સ્કેલ્પિંગ અને સ્વિંગ ટ્રેડિંગ માટે બનાવેલ છે, જે ઝડપી ટ્રેડ્સ અને લાંબા-કાળની વ્યૂહરચનાઓ માટે સચોટ સિગ્નલો પૂરા પાડે છે.</strong>",
    indicator_scalp_price_title: "CRM સ્કેલ્પ / સ્વિંગ સૂચક",
    main_heading_demand: "💡 CRM MTF / ડિમાન્ડ સપ્લાઇ– <span class='highlight'>સરળ સ્કેલ્પ્સ. રણનીતિગત સ્વિંગ્સ</span> 💡",
    main_heading_scalp: "💡 CRM સ્કેલ્પ/ સ્વિંગ– <span class='highlight'>સરળ સ્કેલ્પ્સ. રણનીતિગત સ્વિંગ્સ</span> 💡"
  },
  mr: {
    // Shared Translations
    title: "क्रिएटिव्ह रायझिंग माइंड्स",
    brand_name: "क्रिएटिव्ह रायझिंग माइंड्स",
    nav_home: "होम",
    nav_indicators: "इंडिकेटर",
    nav_pricing: "किंमत",
    nav_contact: "संपर्क",
    footer_copyright: "© 2025 क्रिएटिव्ह रायझिंग माइंड्स. सर्व हक्क राखीव.",
    // indicator1.html Translations
    indicator_title: "CRM ट्रेंड अ‍ॅनालायझर",
    view_tradingview: "📈 ट्रेडिंगव्ह्यूवर बघा",
    main_heading_trend: "💡 CRM ट्रेंड अ‍ॅनालायझर प्रो– <span class='highlight'>स्मार्ट एंट्री लेव्हल अलर्ट टूल</span> 💡",
    subheading: "एंट्री-लेव्हल | मल्टी-टाइमफ्रेम | सर्व सेगमेंट सपोर्ट",
    feature_breakout_title: "✅ ब्रेकआउट-आधारित ट्रेडिंग सिस्टम",
    feature_breakout_1: "<span class='highlight'>कस्टम प्राइस स्ट्रक्चर</span> आणि <span class='highlight'>मूव्हिंग एव्हरेज लॉजिक</span> वापरून ब्रेकआउट झोन शोधते",
    feature_breakout_2: "मुख्य उच्च/निम्न आधारावर <span class='highlight'>लवकर प्री-एंट्री संकेत</span> दाखवते",
    feature_breakout_3: "<span class='highlight'>एंट्री, स्टॉप लॉस, TP1, TP2, आणि TP3</span> आपोआप मोजते",
    feature_trend_engine_title: "✅ डायनॅमिक ट्रेंड इंजिन",
    feature_trend_engine_1: "मोमेंटम अ‍ॅक्सलरेशन लॉजिक वापरून अ‍ॅडॅप्टिव्ह ट्रेंड लाइन्स",
    feature_trend_engine_2: "ट्रेंडच्या वेगावर आधारित कँडलचा रंग दर्शवणे",
    feature_trend_engine_3: "ग्रेडियंटची तीव्रता ट्रेंडची ताकद आणि स्थिरता दर्शवते",
    feature_timeframe_title: "✅ मल्टी-टाइमफ्रेम सपोर्ट",
    feature_timeframe_1: "दैनिक/साप्ताहिक उच्च, निम्न आणि बंद पातळी दर्शवते",
    feature_timeframe_2: "टॉप-डाउन मार्केट संदर्भ वापरून निर्णय घ्या",
    feature_timeframe_3: "ऐतिहासिक पातळी टॉगल करा + लेबल्सचा आकार बदला",
    feature_risk_management_title: "✅ जोखीम आणि लक्ष्य व्यवस्थापन",
    feature_risk_management_1: "एकाधिक संगमांवर आधारित आपोआप मोजलेले एंट्री, SL, TP1, TP2, TP3",
    feature_risk_management_2: "रिअल-टाइम निर्णय घेण्यासाठी स्पष्ट रेखा आणि पातळ्या",
    feature_risk_management_3: "<span class='highlight'>'फक्त शेवटचे सिग्नल'</span> किंवा <span class='highlight'>'सर्व सिग्नल्स'</span> मोडमधून निवडा:",
    feature_risk_management_4: "✅ फक्त नवीनतम ट्रेडसह स्वच्छ चार्ट",
    feature_risk_management_5: "✅ पूर्ण सिग्नल इतिहासासह सहजपणे बॅक टेस्ट",
    feature_technical_tools_title: "✅ बिल्ट-इन तांत्रिक साधने",
    feature_technical_tools_1: "कस्टम- स्टाइल्ड <span class='highlight'>VWAP ओव्हरले</span>",
    feature_technical_tools_2: "समर्थन/प्रतिरोधासाठी मागणी आणि पुरवठा क्षेत्र",
    feature_technical_tools_3: "मोमेंटम ट्रॅकिंगसह एकाधिक अ‍ॅडॅप्टिव्ह MA",
    feature_technical_tools_4: "ताकद पुष्टिकरणासाठी MA ग्रेडियंट",
    feature_signal_display_title: "✅ स्मार्ट सिग्नल डिस्प्ले",
    feature_signal_display_1: "एंट्री लेबल्ससह डायनॅमिक खरेदी/विक्री मार्कर",
    feature_signal_display_2: "झटपट दृश्य समजण्यासाठी रंग-कोडेड SL/TP रेषा",
    feature_signal_display_3: "पर्यायी: मानक कँडल रंग वापरा",
    feature_signal_display_4: "दृश्य सुखसोयींसाठी थीम सानुकूल करा",
    feature_timeframes_title: "🕒 शिफारस केलेले टाइमफ्रेम्स",
    feature_timeframes_1: "<span class='highlight'>3 मिनिट / 5 मिनिट → इंट्राडे आणि स्काल्पिंग</span>",
    feature_timeframes_2: "<span class='highlight'>दैनिक चार्ट → स्विंग / पोझिशनल सेटअप्स</span>",
    feature_learning_note_title: "⚠️ महत्त्वाची शिकण्याची नोट",
    feature_learning_note_intro: "हे साधन तुमच्या शिक्षण आणि धोरण विकासासाठी आहे. याचा उपयोग यासह करा:",
    feature_learning_note_1: "स्पष्ट ट्रेडिंग योजना",
    feature_learning_note_2: "शिस्तबद्ध जोखीम व्यवस्थापन",
    feature_learning_note_3: "योग्य पोझिशन साइझिंग (एकल प्रमाणापासून सुरु)",
    feature_learning_note_4: "कडक स्टॉप लॉस नियम",
    feature_learning_note_5: "जेव्हा जोखीम-ते-बक्षीस गुणोत्तर अनुकूल असेल तेव्हाच ट्रेड",
    feature_learning_note_6: "बाजूच्या किंवा विरोधी बाजारात, ट्रेड न करणे हा सर्वोत्तम ट्रेड असू शकतो",
    feature_learning_note_7: "खरा संपत्ती निर्माण केवळ दीर्घकालीन गुंतवणुकीद्वारे होतो",
    feature_learning_note_8: "शिस्तबद्ध जोखीम व्यवस्थापनासाठी, इंट्राडे एक्सपोजर तुमच्या भांडवलाच्या 10% पर्यंत मर्यादित ठेवा",
    feature_beginner_path_title: "🔰 नवशिक्या मार्ग:",
    feature_beginner_path_1: "2 महिन्यांसाठी पेपर ट्रेडिंगपासून सुरूवात करा.",
    feature_beginner_path_2: "नंतर छोट्या भांडवलासह (₹3,000 किंवा कमी) इक्विटी ट्रेड्स करा.",
    feature_beginner_path_3: "नुकसान ₹50 – ₹100/दिवसापर्यंत मर्यादित ठेवा. दबावाशिवाय शिका.",
    feature_beginner_path_4: "सुरवातीला ऑप्शन/फ्यूचर्स ट्रेडिंग टाळा — ऑप्शन्स उच्च-जोखीम साधने आहेत आणि त्यासाठी प्रगत समज आवश्यक आहे.",
    feature_beginner_path_quote: "<span class='highlight'>💡 “आधी शिका, नंतर कमवा.” तुमच्या भांडवलाचा वाढ किंवा नुकसान पूर्णपणे तुमच्या नियंत्रणात आहे.</span>",
    feature_dark_mode_title: "🎨 डार्क मोडसाठी ऑप्टिमाइझ → आता पूर्णपणे सानुकूल",
    feature_dark_mode_desc: "पूर्वी डार्क मोडसाठी तयार, आता वापरकर्ता-निवडलेल्या रंग पर्यायांसह सुधारित, वैयक्तिक आणि स्पष्ट दृश्य अनुभवासाठी.",
    feature_trend_confluence_title: "📈 डायनॅमिक ट्रेंड कॉन्फ्ल्यूएन्स व्हिज्युअल",
    feature_trend_confluence_desc: "ट्रेंड-फॉलोइंग व्हिज्युअल लेयर सादर करत आहे जे तुम्हाला आत्मविश्वास आणि स्पष्टतेसह ट्रेंड्स फॉलो करण्यात मदत करते.",
    feature_alerts_title: "🔔 रिअल-टाइम अलर्ट्स इंटिग्रेटेड",
    feature_alerts_desc: "कधीही ट्रेड चुकवू नका. सर्व महत्त्वाच्या ट्रेड सिग्नल्स आणि परिस्थितींसाठी बिल्ट-इन अलर्ट्ससह अपडेट रहा.",
    feature_disclaimer_title: "⚠️ डिस्क्लेमर",
    feature_disclaimer_1: "हा इंडिकेटर आणि सामग्री केवळ शैक्षणिक आणि माहितीच्या उद्देशाने आहे. हे याचा अर्थ आर्थिक, गुंतवणूक किंवा कायदेशीर सल्ला देत नाही. सर्व मते संशोधनावर आधारित वैयक्तिक अर्थघटना आहेत आणि कोणतीही सिक्युरिटी खरेदी, विक्री किंवा धरून ठेवण्याची शिफारस नाहीत.",
    feature_disclaimer_2: "गुंतवणूक निर्णय घेण्यापूर्वी नेहमी SEBI-नोंदणीकृत सल्लागार किंवा प्रमाणित आर्थिक नियोजकाचा सल्ला घ्या. निर्माता दर्शकांनी घेतलेल्या कोणत्याही आर्थिक नुकसान किंवा निर्णयासाठी जबाबदार नाही.",
    feature_disclaimer_3: "हे साधन तुमच्या स्वतःच्या धोरणाच्या समर्थनासाठी वापरा — स्वतंत्र ट्रेडिंग सिस्टम म्हणून नाही.",
    feature_disclaimer_4: "<strong>आनंदी ट्रेडिंग, चीअर्स!</strong>",
    // Existing translations...
    video_fallback: "तुमचा ब्राउझर व्हिडिओ टॅगला सपोर्ट करत नाही.",
    hero_title: "ट्रेडर्ससाठी तयार केलेले जे तर्काचे अनुसरण करतात, नशीबाचे नाही.",
    hero_subtitle: "सिग्नल शोधा. गोंगाट टाळा. ट्रेंडवर वर्चस्व मिळवा.",
    hero_btn_explore: "योजना शोधा",
    hero_btn_contact: "आमच्याशी संपर्क साधा",
    indicators_title: "आमचे क्रिएटिव्ह इंडिकेटर (प्रिमियम)",
    indicator_trend_title: 'CRM ट्रेंड अ‍ॅनालायझर प्रो (मोफत चाचणी)',
    indicator_trend_desc: "<strong>CRM ट्रेंड अ‍ॅनालायझर प्रो मूव्हिंग एव्हरेज, ट्रेंड ऑसिलेटर्स, व्होलॅटिलिटी टार्गेट्स आणि सप्लाय-डिमांड झोन एकत्रित करून ट्रेडर्सना एंट्रीज आणि एक्झिट्सचा वेळ अचूकपणे ठरवण्यास मदत करते.</strong>",
    indicator_learn_more: "अधिक जाणून घ्या",
    indicator_scalp_title: "CRM<br>स्कॅल्प / स्विंग",
    indicator_scalp_desc: "",
    indicator_demand_title: "CRM MTF/डिमांड सप्लाय",
    indicator_demand_desc: "<strong>CRM MTF/डिमांड सप्लाय हे एक स्मार्ट ट्रेंड-ट्रॅकिंग टूल आहे जे मल्टी-टाइमफ्रेम ट्रेंड टेबल दाखवते आणि डिमांड/सप्लाय झोन ऑटो-प्रॉट्स करते—जेणेकरून तुम्ही चार्ट बदलता येणार नाही तोपर्यंत बाजाराची दिशा आणि महत्त्वाचे स्तर शोधू शकता.</strong>",
    indicator_screener_title: "CRM स्टॉक स्क्रीनर",
    indicator_screener_desc: "",
    indicator_option_title: "CRM ऑप्शन चेन डीकोडर",
    indicator_option_desc: "",
    pricing_title: "किंमत योजना",
    pricing_table_indicator: "इंडिकेटर",
    pricing_table_monthly: "मासिक",
    pricing_table_quarterly: "तिमाही",
    pricing_table_half_yearly: "अर्ध-वार्षिक",
    pricing_table_yearly: "वार्षिक",
    pricing_trend_status: "<strong><span style='color: #ff9800'>मर्यादित काळासाठी मोफत वापरा – चुकवू नका!</span></strong>",
    pricing_coming_soon: "लवकरच येत आहे! आमची माना तुमच्यासाठी काहीतरी शक्तीशाली तयार करत आहे.",
    feedback_text: "<span style='color: #ff9800'>आम्हाला आमच्या इंडिकेटरांवर तुमचा मौल प्राय ऐकायला आवडेल! WhatsApp, ईमेल किंवा टेलिग्रामद्वारे तुमचे विचार आमच्यासोबत शेअर करा.</span>",
    feedback_offer: "तुमचा प्राय शेअर करा आणि आमच्या प्रीमियम इंडिकेटराच्या एका महिन्याच्या मोफत प्रवेशाची संधी जिंका!",
    contact_title: "संपर्क आणि पेमेंट",
    contact_subtitle: "सब्स्क्रिप्शन, समर्थन किंवा पेमेंट प्रश्नांसाठी संपर्क साधा.",
    telegram_handle: "@CREATIVE RISING MINDS",
    upi_title: "UPI पेमेंट",
    upi_instruction: "UPI ID वापरून पेमेंट करा:<br><span>riazshaikh005@okicici</span>",
    upi_confirmation: "WhatsApp किंवा टेलिग्रामद्वारे पुष्टिकरण शेअर करा.",
    //footer
    footer_social_media: "आम्हाला सोशल मीडियावर फॉलो करा",
    footer_contact_us: "आमच्याशी संपर्क साधा",
    footer_email_label: "creativerisingminds@gmail.com",
    footer_phone_label: "+91 9930752555 (चौकशी)",
    footer_quick_links: "द्रुत लिंक्स",
    footer_policies: "धोरणे आणि अनुपालन",
    footer_home: "होम",
    footer_disclaimer: "डिस्क्लेमर",
    footer_privacy_policy: "गोपनीयता धोरण",
    footer_terms_conditions: "नियम आणि अटी",
    // New Disclaimer Page Translations
    disclaimer_title: "डिस्क्लेमर | CRM",
    disclaimer_heading: "डिस्क्लेमर",
    risk_warning: "सिक्युरिटीज मार्केटमधील गुंतवणूक बाजारातील जोखमींना अधीन आहे, गुंतवणूक करण्यापूर्वी सर्व संबंधित कागदपत्रे काळजीपूर्वक वाचा.",
    section_intro: "<strong>क्रिएटिव्ह रायझिंग माइंड्स (CRM)</strong> मध्ये आपले स्वागत आहे. या वेबसाइटद्वारे प्रदान केलेली सर्व सामग्री आणि सेवा केवळ <strong>शैक्षणिक आणि माहितीच्या उद्देशाने</strong> आहेत.",
    section_not_financial_advice_title: "आर्थिक सल्ला नाही",
    section_not_financial_advice: "आम्ही SEBI नोंदणीकृत सल्लागार नाही. या प्लॅटफॉर्मवर शेअर केलेली कोणतीही माहिती, ज्यामध्ये आमची साधने, निर्देशक, ट्यूटोरियल्स, किंवा मते समाविष्ट आहेत, ती आर्थिक सल्ला किंवा कोणतीही सिक्युरिटी खरेदी, विक्री किंवा धरून ठेवण्याची शिफारस म्हणून गणली जाऊ नये.",
    section_use_at_own_risk_title: "तुमच्या स्वतःच्या जोखमीवर वापरा",
    section_use_at_own_risk: "शेअर बाजारात ट्रेडिंगमध्ये जोखीम समाविष्ट आहे. भूतकाळातील कामगिरी भविष्यातील परताव्याची हमी देत नाही. तुम्ही तुमच्या गुंतवणूक निर्णयांसाठी पूर्णपणे जबाबदार आहात, आणि CRM किंवा त्याची टीम कोणत्याही नुकसानीसाठी जबाबदार राहणार नाही.",
    section_accuracy_content_title: "अचूकता आणि सामग्री",
    section_accuracy_content: "आम्ही अचूक आणि अद्ययावत माहिती प्रदान करण्याचा प्रयत्न करतो, परंतु आम्ही कोणत्याही सामग्रीच्या अचूकते, पूर्णतेची, किंवा विश्वसनीयतेची कोणतीही हमी देत नाही. त्यावर कृती करण्यापूर्वी नेहमी माहिती स्वतंत्रपणे सत्यापित करा.",
    section_affiliate_content_title: "एफिलिएट आणि प्रचारात्मक सामग्री",
    section_affiliate_content: "आमच्या वेबसाइटवर एफिलिएट लिंक्स किंवा प्रचारात्मक सामग्री असू शकते. तुम्ही या लिंक्स वापरल्यास आम्ही थोडे कमिशन मिळवू शकतो, तुम्हाला कोणताही अतिरिक्त खर्च न करता. तथापि, आम्ही फक्त ती साधने किंवा प्लॅटफॉर्म्सचे प्रचार करतो जे आम्हाला वापरकर्त्यांसाठी मौल्यवान वाटतात.",
    section_third_party_links_title: "तृतीय-पक्ष लिंक्स",
    section_third_party_links: "या साइटवर तृतीय-पक्ष वेबसाइट्सच्या लिंक्स असू शकतात. आम्ही बाह्य साइट्सच्या सामग्री, धोरणे, किंवा पद्धतींसाठी जबाबदार नाही. कृपया त्यांच्या संबंधित नियम आणि डिस्क्लेमर्सचे पुनरावलोकन करा.",
    section_consent_title: "संमती",
    section_consent: "या वेबसाइटचा वापर करून, तुम्ही या डिस्क्लेमरला संमती देता आणि त्याच्या अटींशी सहमत आहात.",
    footer_note_contact: "जर तुम्हाला या डिस्क्लेमरबद्दल कोणतेही प्रश्न असतील, तर कृपया आमच्याशी संपर्क साधा <a href='mailto:creativerisingminds@gmail.com'>creativerisingminds@gmail.com</a> वर.",
    footer_note_updated: "शेवटचे अद्ययावत: जुलै 28, 2025",
    // New Privacy Policy Page Translations
    privacy_title: "गोपनीयता धोरण | CRM",
    privacy_policy_heading: "गोपनीयता धोरण",
    section_intro: "<strong>क्रिएटिव्ह रायझिंग माइंड्स (CRM)</strong> येथे, आम्ही तुमच्या गोपनीयतेचे मूल्य ठेवतो आणि तुमच्या वैयक्तिक माहितीचे संरक्षण करण्यासाठी कटिबद्ध आहोत.",
    section_info_collect_title: "आम्ही गोळा करतो ती माहिती",
    section_info_collect: "जेव्हा तुम्ही फॉर्म्स, न्यूजलेटर साइनअप्स, किंवा आमच्याशी संवादाद्वारे स्वेच्छेने सादर करता तेव्हा आम्ही वैयक्तिक ओळख माहिती (जसे की तुमचे नाव, ईमेल पत्ता आणि संपर्क तपशील) गोळा करू शकतो.",
    section_how_use_info_title: "आम्ही तुमच्या माहितीचा वापर कसा करतो",
    section_how_use_info: "आम्ही गोळा केलेली माहिती यासाठी वापरली जाऊ शकते:",
    section_how_use_info_item1: "तुमच्या चौकशी आणि समर्थन विनंत्यांना प्रतिसाद देण्यासाठी",
    section_how_use_info_item2: "अपडेट्स, ट्यूटोरियल्स, किंवा साधनांबद्दल वेळोवेळी ईमेल पाठवण्यासाठी",
    section_how_use_info_item3: "आमच्या वेबसाइटच्या कामगिरी आणि वापरकर्ता अनुभवात सुधारणा करण्यासाठी",
    section_cookies_title: "कुकीज",
    section_cookies: "आम्ही तुमचा ब्राउझिंग अनुभव वाढवण्यासाठी कुकीज वापरू शकतो. तुम्ही तुमच्या ब्राउझर सेटिंग्जद्वारे कुकीज अक्षम करणे निवडू शकता.",
    section_third_party_services_title: "तृतीय-पक्ष सेवा",
    section_third_party_services: "आम्ही अॅनालिटिक्स किंवा एफिलिएट प्लॅटफॉर्म्ससारख्या तृतीय-पक्ष साधनांचा वापर करू शकतो. या सेवा त्यांच्या स्वतःच्या गोपनीयता धोरणांनुसार डेटा गोळा करू शकतात. आम्ही या तृतीय-पक्ष साइट्सच्या डेटा पद्धतींसाठी जबाबदार नाही.",
    section_data_security_title: "डेटा सुरक्षा",
    section_data_security: "आम्ही तुमच्या डेटाचे संरक्षण करण्यासाठी वाजवी उपाययोजना करतो, परंतु इंटरनेटवरील कोणतेही प्रसारण 100% सुरक्षित नाही. आम्ही पूर्ण सुरक्षिततेची हमी देऊ शकत नाही.",
    section_external_links_title: "बाह्य लिंक्स",
    section_external_links: "आमच्या वेबसाइटवर इतर वेबसाइट्सच्या लिंक्स असू शकतात. आम्ही त्या साइट्सच्या गोपनीयता पद्धतींसाठी जबाबदार नाही आणि तुम्हाला त्यांच्या गोपनीयता धोरणांचे पुनरावलोकन करण्यास प्रोत्साहित करतो.",
    section_your_consent_title: "तुमची संमती",
    section_your_consent: "आमच्या वेबसाइटचा वापर करून, तुम्ही या गोपनीयता धोरणाला संमती देता आणि त्याच्या अटींशी सहमत आहात.",
    section_changes_policy_title: "या धोरणात बदल",
    section_changes_policy: "आम्ही या धोरणात वेळोवेळी अद्ययावत करू शकतो. बदल या पृष्ठावर अद्ययावत पुनरावृत्ती तारखेसह पोस्ट केले जातील.",
    footer_note_contact: "जर तुम्हाला या गोपनीयता धोरणाबद्दल कोणतेही प्रश्न असतील, तर आमच्याशी संपर्क साधा <a href='mailto:creativerisingminds@gmail.com'>creativerisingminds@gmail.com</a> वर.",
    footer_note_updated: "शेवटचे अद्ययावत: जुलै 28, 2025",
    // New Terms and Conditions Page Translations
    tnc_title: "नियम आणि अटी | CRM",
    terms_conditions_heading: "नियम आणि अटी",
    section_intro: "<strong>क्रिएटिव्ह रायझिंग माइंड्स (CRM)</strong> मध्ये आपले स्वागत आहे. या वेबसाइटवर प्रवेश करून, तुम्ही खालील नियम आणि अटींचे पालन करण्यास आणि त्यांना बांधील राहण्यास सहमती देता. जर तुम्ही या अटींच्या कोणत्याही भागाशी असहमत असाल, तर कृपया आमच्या वेबसाइटचा वापर करू नका.",
    section_use_content_title: "सामग्रीचा वापर",
    section_use_content: "या वेबसाइटवरील सर्व सामग्री, ज्यामध्ये ट्रेडिंग निर्देशक, ट्यूटोरियल्स आणि ब्रँडिंग यांचा समावेश आहे, ती CRM ची मालमत्ता आहे आणि कॉपीराइट कायद्यांद्वारे संरक्षित आहे. तुम्ही पूर्वलिखित संमतीशिवाय कोणत्याही सामग्रीचे पुनरुत्पादन, वितरण किंवा शोषण करू शकत नाही.",
    section_disclaimer_title: "डिस्क्लेमर",
    section_disclaimer: "या वेबसाइटवर प्रदान केलेले सर्व ट्रेडिंग निर्देशक, सिग्नल्स किंवा साधने केवळ शैक्षणिक आणि माहितीच्या उद्देशाने आहेत. आम्ही नोंदणीकृत आर्थिक सल्लागार नाही आणि कोणताही गुंतवणूक सल्ला देत नाही. तुम्ही तुमच्या ट्रेडिंग निर्णयांसाठी पूर्णपणे जबाबदार आहात.",
    section_payments_subscriptions_title: "चुकारे आणि सदस्यता",
    section_payments_subscriptions: "आमच्या उत्पादनांसाठी किंवा सेवांसाठी केलेले सर्व चुकारे अंतिम आणि परतावायोग्य नाहीत, जोपर्यंत अन्यथा नमूद केलेले नाही. तुम्ही आमच्या प्लॅटफॉर्मवर खरेदी करताना अचूक आणि पूर्ण चुकवणूक तपशील प्रदान करण्यास सहमती देता.",
    section_limitation_liability_title: "जबाबदारीची मर्यादा",
    section_limitation_liability: "CRM आमच्या वेबसाइट किंवा उत्पादनांच्या वापरामुळे उद्भवणाऱ्या कोणत्याही थेट, अप्रत्यक्ष किंवा परिणामी नुकसान किंवा हानीसाठी जबाबदार राहणार नाही. तुम्ही आमच्या सेवांचा वापर तुमच्या स्वतःच्या जोखमीवर करायला सहमती देता.",
    section_user_conduct_title: "वापरकर्ता आचरण",
    section_user_conduct: "तुम्ही या साइटचा वापर कोणत्याही बेकायदेशीर हेतूसाठी किंवा CRM किंवा इतर वापरकर्त्यांना हानी पोहोचवू शकेल अशा कोणत्याही प्रकारे करणार नाही यास सहमती देता. या साइटचा गैरवापर तुमच्या प्रवेशाच्या समाप्तीला कारणीभूत ठरू शकतो.",
    section_external_links_title: "बाह्य लिंक्स",
    section_external_links: "आम्ही तृतीय-पक्ष वेबसाइट्सच्या लिंक्स समाविष्ट करू शकतो. या लिंक्स तुमच्या सोयीसाठी प्रदान केल्या आहेत आणि आमच्या समर्थनाचे संकेत देत नाहीत. आम्ही या बाह्य साइट्सच्या सामग्री किंवा पद्धतींसाठी जबाबदार नाही.",
    section_modifications_title: "सुधारणा",
    section_modifications: "आम्ही या नियम आणि अटींमध्ये वेळोवेळी सुधारणा करू शकतो. नवीनतम आवृत्ती नेहमी या पृष्ठावर पोस्ट केली जाईल. आमच्या साइटचा सतत वापर या बदलांच्या स्वीकृतीला सूचित करतो.",
    section_governing_law_title: "शासकीय कायदा",
    section_governing_law: "या अटी भारताच्या कायद्यांनुसार शासित आणि त्यांचे अर्थ लावले जातात. कोणत्याही वादविवादावर मुंबईतील न्यायालयांचे विशेष अधिकारक्षेत्र असेल.",
    footer_note_contact: "जर तुम्हाला या नियम आणि अटींबद्दल कोणतेही प्रश्न असतील, तर कृपया आमच्याशी संपर्क साधा <a href='mailto:creativerisingminds@gmail.com'>creativerisingminds@gmail.com</a> वर.",
    footer_note_updated: "शेवटचे अद्ययावत: जुलै 28, 2025",
    free_indicators_title: "आमचे मोफत इंडिकेटर",
    indicator_momentum_title: "CRM मॉमेंटम शोधक",
    indicator_volatility_title: "CRM व्होलॅटिलिटी ट्रॅकर",
    indicator_scalp_desc: "<strong>CRM स्कॅल्प/स्विंग हे एक बहुमुखी इंडिकेटर आहे जो स्कॅल्पिंग आणि स्विंग ट्रेडिंगसाठी डिझाइन केलेला आहे, जे जलद ट्रेड्स आणि दीर्घकालीन रणनीतींसाठी अचूक सिग्नल्स देते.</strong>",
    indicator_scalp_price_title: "CRM स्कॅल्प / स्विंग इंडिकेटर",
    main_heading_demand: "💡 CRM MTF / डिमांड सप्लाय– <span class='highlight'>सुकर स्कॅल्प्स. रणनीतीपूर्ण स्विंग्स</span> 💡",
    main_heading_scalp: "💡 CRM स्कॅल्प/ स्विंग– <span class='highlight'>सुकर स्कॅल्प्स. रणनीतीपूर्ण स्विंग्स</span> 💡"
  }
};

function changeLanguage() {
  const select = document.getElementById('language-select');
  const selectedLang = select.value;

  // Update all elements with data-translate attributes
  document.querySelectorAll('[data-translate]').forEach(element => {
    const key = element.getAttribute('data-translate');
    if (translations[selectedLang][key]) {
      element.innerHTML = translations[selectedLang][key];
    }
  });

  // Update document language
  document.documentElement.lang = selectedLang;
}

// Initialize translation on page load
document.addEventListener('DOMContentLoaded', () => {
  changeLanguage();
});